// Shared wasm-inline loader: an esbuild plugin for the Obsidian bundle and a vite/vitest
// plugin for tests. Inlines the .wasm as base64 (plan KTD5 — no external asset fetch, which
// fails on Obsidian mobile with ERR_FILE_NOT_FOUND) and instantiates it synchronously.
//
// Live shims (imports whose name starts with `__wbg_`) are imported from the companion
// *_bg.js module; every other import is generically dead in wasm-bindgen glue and becomes a
// throwing stub so a future ABI change fails loudly instead of silently misbehaving.
import { readFileSync } from "node:fs";
import { dirname } from "node:path";

function moduleCode(wasmPath) {
	const bytes = readFileSync(wasmPath);
	const mod = new WebAssembly.Module(bytes);
	const imports = WebAssembly.Module.imports(mod);

	const byModule = new Map();
	for (const im of imports) {
		if (!byModule.has(im.module)) byModule.set(im.module, []);
		byModule.get(im.module).push(im.name);
	}

	const lines = ["// Generated by scripts/wasm-inline.mjs — do not edit."];
	const tables = [];
	for (const [modName, names] of byModule) {
		const live = names.filter((n) => n.startsWith("__wbg_"));
		const dead = names.filter((n) => !n.startsWith("__wbg_"));
		for (const n of live) {
			lines.push(`import { ${n} } from ${JSON.stringify(modName)};`);
		}
		for (const n of dead) {
			lines.push(`function ${n}() { throw new Error("wasm-inline: dead import ${n} invoked"); }`);
		}
		tables.push(`${JSON.stringify(modName)}: { ${[...live, ...dead].join(", ")} }`);
	}

	lines.push(`const __B64 = ${JSON.stringify(bytes.toString("base64"))};`);
	lines.push(
		"function __bytes() { const bin = atob(__B64); const u8 = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i); return u8; }"
	);
	lines.push(`const __instance = new WebAssembly.Instance(new WebAssembly.Module(__bytes()), { ${tables.join(", ")} });`);
	lines.push("const __e = __instance.exports;");
	for (const e of WebAssembly.Module.exports(mod)) {
		lines.push(`export const ${e.name} = __e[${JSON.stringify(e.name)}];`);
	}
	lines.push("export default __e;");
	return lines.join("\n");
}

export const esbuildWasmInline = {
	name: "wasm-inline",
	setup(build) {
		build.onLoad({ filter: /\.wasm$/ }, (args) => ({
			contents: moduleCode(args.path),
			loader: "js",
			resolveDir: dirname(args.path),
		}));
	},
};

export const viteWasmInline = {
	name: "wasm-inline",
	enforce: "pre",
	load(id) {
		if (id.endsWith(".wasm") && !id.includes("?")) {
			try {
				return moduleCode(id);
			} catch {
				return null;
			}
		}
		return null;
	},
};